name: norminette
on: [push, pull_request]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools and dependencies
        run: |
          pip3 install --upgrade pip setuptools
          pip3 install norminette

      - name: Test Norm
        run: | 
          python3 -m norminette
